<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Live Test Cases Suite" duration-ms="155388" started-at="2015-12-06T15:01:05Z" finished-at="2015-12-06T15:03:40Z">
    <groups>
    </groups>
    <test name="Live Tests" duration-ms="155388" started-at="2015-12-06T15:01:05Z" finished-at="2015-12-06T15:03:40Z">
      <class name="TestCases.TestCase3">
        <test-method status="PASS" signature="setUp()[pri:0, instance:TestCases.TestCase3@7f63425a]" name="setUp" is-config="true" duration-ms="14" started-at="2015-12-06T20:32:22Z" finished-at="2015-12-06T20:32:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="ValidNonAuthorisedParentLogin(java.lang.String)[pri:0, instance:TestCases.TestCase3@7f63425a]" name="ValidNonAuthorisedParentLogin" duration-ms="36559" started-at="2015-12-06T20:32:22Z" finished-at="2015-12-06T20:32:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Live Test Cases]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login � How to Train Your Dragon Game � School of Dragons] but found [Login – How to Train Your Dragon Game – School of Dragons]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login � How to Train Your Dragon Game � School of Dragons] but found [Login – How to Train Your Dragon Game – School of Dragons]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at Pages.LoginPage.verifyLoginPageTitle(LoginPage.java:33)
	at TestCases.TestCase3.ValidNonAuthorisedParentLogin(TestCase3.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidNonAuthorisedParentLogin -->
        <test-method status="PASS" signature="afterTest(org.testng.ITestResult)[pri:0, instance:TestCases.TestCase3@7f63425a]" name="afterTest" is-config="true" duration-ms="1160" started-at="2015-12-06T20:32:59Z" finished-at="2015-12-06T20:33:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidNonAuthorisedParentLogin status=FAILURE method=TestCase3.ValidNonAuthorisedParentLogin(java.lang.String)[pri:0, instance:TestCases.TestCase3@7f63425a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestCases.TestCase3@7f63425a]" name="tearDown" is-config="true" duration-ms="482" started-at="2015-12-06T20:33:00Z" finished-at="2015-12-06T20:33:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCases.TestCase3 -->
      <class name="TestCases.TestCase4">
        <test-method status="PASS" signature="setUp()[pri:0, instance:TestCases.TestCase4@36d64342]" name="setUp" is-config="true" duration-ms="6" started-at="2015-12-06T20:33:01Z" finished-at="2015-12-06T20:33:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="ValidNonAuthorisedPlayerLogin(java.lang.String)[pri:0, instance:TestCases.TestCase4@36d64342]" name="ValidNonAuthorisedPlayerLogin" duration-ms="37890" started-at="2015-12-06T20:33:01Z" finished-at="2015-12-06T20:33:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Live Test Cases]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login � How to Train Your Dragon Game � School of Dragons] but found [Login – How to Train Your Dragon Game – School of Dragons]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login � How to Train Your Dragon Game � School of Dragons] but found [Login – How to Train Your Dragon Game – School of Dragons]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at Pages.LoginPage.verifyLoginPageTitle(LoginPage.java:33)
	at TestCases.TestCase4.ValidNonAuthorisedPlayerLogin(TestCase4.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidNonAuthorisedPlayerLogin -->
        <test-method status="PASS" signature="afterTest(org.testng.ITestResult)[pri:0, instance:TestCases.TestCase4@36d64342]" name="afterTest" is-config="true" duration-ms="1185" started-at="2015-12-06T20:33:38Z" finished-at="2015-12-06T20:33:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidNonAuthorisedPlayerLogin status=FAILURE method=TestCase4.ValidNonAuthorisedPlayerLogin(java.lang.String)[pri:0, instance:TestCases.TestCase4@36d64342] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestCases.TestCase4@36d64342]" name="tearDown" is-config="true" duration-ms="488" started-at="2015-12-06T20:33:40Z" finished-at="2015-12-06T20:33:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCases.TestCase4 -->
      <class name="TestCases.TestCase1">
        <test-method status="PASS" signature="setUp()[pri:0, instance:TestCases.TestCase1@880ec60]" name="setUp" is-config="true" duration-ms="162" started-at="2015-12-06T20:31:05Z" finished-at="2015-12-06T20:31:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="ValidAuthorisedPlayerLogin(java.lang.String)[pri:0, instance:TestCases.TestCase1@880ec60]" name="ValidAuthorisedPlayerLogin" duration-ms="37559" started-at="2015-12-06T20:31:05Z" finished-at="2015-12-06T20:31:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Live Test Cases]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login � How to Train Your Dragon Game � School of Dragons] but found [Login – How to Train Your Dragon Game – School of Dragons]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login � How to Train Your Dragon Game � School of Dragons] but found [Login – How to Train Your Dragon Game – School of Dragons]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at Pages.LoginPage.verifyLoginPageTitle(LoginPage.java:33)
	at TestCases.TestCase1.ValidAuthorisedPlayerLogin(TestCase1.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidAuthorisedPlayerLogin -->
        <test-method status="PASS" signature="afterTest(org.testng.ITestResult)[pri:0, instance:TestCases.TestCase1@880ec60]" name="afterTest" is-config="true" duration-ms="1273" started-at="2015-12-06T20:31:43Z" finished-at="2015-12-06T20:31:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidAuthorisedPlayerLogin status=FAILURE method=TestCase1.ValidAuthorisedPlayerLogin(java.lang.String)[pri:0, instance:TestCases.TestCase1@880ec60] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestCases.TestCase1@880ec60]" name="tearDown" is-config="true" duration-ms="653" started-at="2015-12-06T20:31:44Z" finished-at="2015-12-06T20:31:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCases.TestCase1 -->
      <class name="TestCases.TestCase2">
        <test-method status="PASS" signature="setUp()[pri:0, instance:TestCases.TestCase2@3f3afe78]" name="setUp" is-config="true" duration-ms="10" started-at="2015-12-06T20:31:44Z" finished-at="2015-12-06T20:31:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="ValidAuthorisedParentLogin(java.lang.String)[pri:0, instance:TestCases.TestCase2@3f3afe78]" name="ValidAuthorisedParentLogin" duration-ms="36083" started-at="2015-12-06T20:31:44Z" finished-at="2015-12-06T20:32:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Live Test Cases]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login � How to Train Your Dragon Game � School of Dragons] but found [Login – How to Train Your Dragon Game – School of Dragons]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login � How to Train Your Dragon Game � School of Dragons] but found [Login – How to Train Your Dragon Game – School of Dragons]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at Pages.LoginPage.verifyLoginPageTitle(LoginPage.java:33)
	at TestCases.TestCase2.ValidAuthorisedParentLogin(TestCase2.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidAuthorisedParentLogin -->
        <test-method status="PASS" signature="afterTest(org.testng.ITestResult)[pri:0, instance:TestCases.TestCase2@3f3afe78]" name="afterTest" is-config="true" duration-ms="1244" started-at="2015-12-06T20:32:21Z" finished-at="2015-12-06T20:32:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidAuthorisedParentLogin status=FAILURE method=TestCase2.ValidAuthorisedParentLogin(java.lang.String)[pri:0, instance:TestCases.TestCase2@3f3afe78] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestCases.TestCase2@3f3afe78]" name="tearDown" is-config="true" duration-ms="599" started-at="2015-12-06T20:32:22Z" finished-at="2015-12-06T20:32:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCases.TestCase2 -->
    </test> <!-- Live Tests -->
  </suite> <!-- Live Test Cases Suite -->
</testng-results>
